### ISSUE TITLE
你好，palette 只能单个值，不然会导致样式出错

### ISSUE THREAD

**Issue by razonyang** [KitSSang/kitssang.github.io#2]
https://github.com/KitSSang/kitssang.github.io/blob/12d0ae9115f2df4e915ab2c704dab8abb7315a90/config/_default/params.toml#L12

刚从issue过来，发现你博客样式不对劲，应该是这个参数设置不正确，这个只能单个值。改成 `blue` 或者 `gray` 都可以。

**Comment by KitSSang** [comment]
万分感谢，我这边试试。本地运行好像是没有问题的，但是部署就有了问题，我这边先修改了试试

**Comment by KitSSang** [comment]
> https://github.com/KitSSang/kitssang.github.io/blob/12d0ae9115f2df4e915ab2c704dab8abb7315a90/config/_default/params.toml#L12
> 
> 刚从issue过来，发现你博客样式不对劲，应该是这个参数设置不正确，这个只能单个值。改成 `blue` 或者 `gray` 都可以。

> 万分感谢，我这边试试。本地运行好像是没有问题的，但是部署就有了问题，我这边先修改了试试
